#! /bin/sh


echo "stop network manager"
sudo service network-manager stop

echo "stop eth0"
sudo ifconfig eth0 down

echo "setup eth0"
sudo ifconfig eth0 HOST_ADDR up

echo "start tftp server"
sudo service tftpd-hpa start

echo "start dhcp server"
sudo service dhcp3-server start

echo "start NFS server"
sudo service nfs-kernel-server start

echo "start minicom"
sudo LANG=C minicom -s

