#! /bin/sh


echo "stop tftp server"
sudo service tftpd-hpa stop

echo "stop dhcp server"
sudo service dhcp3-server stop

echo "stop NFS server"
sudo service nfs-kernel-server stop

echo "stop eth0"
sudo ifconfig eth0 down

echo "start network manager"
sudo service network-manager start

echo "start eth0"
sudo ifconfig eth0 up

